Controllers/BlogPostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using wc_Blog.Helpers;
using wc_Blog.Models;
using PagedList;
using PagedList.Mvc;
using System.Web.UI;
using System.Runtime.CompilerServices;

namespace wc_Blog.Controllers
{
    public class BlogPostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: BlogPosts
        [Authorize(Roles = "Admin, Moderator")]
        public ActionResult Index(int? page, string searchStr)
        {
            ViewBag.Search = searchStr;
            var blogList = IndexSearch(searchStr);

            int pageSize = 10;
            int pageNumber = (page ?? 1); //?? null coalescing operator

            return View(blogList.ToPagedList(pageNumber, pageSize));
        }

        public IQueryable<BlogPost> IndexSearch(string searchStr)
        {
            IQueryable<BlogPost> result = null;
            if(searchStr != null)
            {
                result = db.BlogPosts.AsQueryable();
                result = result.Where(p => p.Title.Contains(searchStr) ||
                                            p.Body.Contains(searchStr) ||
                                            p.Comments.Any(c => c.CommentBody.Contains(searchStr) ||
                                            c.Author.FirstName.Contains(searchStr) ||
                                            c.Author.LastName.Contains(searchStr) ||
                                            c.Author.DisplayName.Contains(searchStr) ||
                                            c.Author.Email.Contains(searchStr)));
            }
            else
            {
                result = db.BlogPosts.AsQueryable();
            }

            return result.OrderByDescending(b => b.Created);
        }

        // GET: BlogPosts/Details/5
        public ActionResult Details(string slug)
        {
            if (String.IsNullOrWhiteSpace(slug))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.FirstOrDefault(p => p.Slug == slug);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // GET: BlogPosts/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }



        // POST: BlogPosts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Title,Body,Abstract,Published,Category")] BlogPost blogPost, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                var slug = StringUtilities.URLFriendly(blogPost.Title);
                if (String.IsNullOrWhiteSpace(slug))
                {
                    ModelState.AddModelError("Title", "Invalid Title");
                    return View(blogPost);
                }
                if (db.BlogPosts.Any(p => p.Slug == slug))
                {
                    ModelState.AddModelError("Title", "The title must be unique");
                    return View(blogPost);
                }
                blogPost.Slug = slug;

                if (ImageUploadValidator.IsWebFriendlyImage(image))
                {
                    var fileName = Path.GetFileName(image.FileName);
                    var justFileName = Path.GetFileNameWithoutExtension(fileName);
                    justFileName = StringUtilities.URLFriendly(justFileName);
                    fileName = $"{justFileName}_{DateTime.Now.Ticks}{Path.GetExtension(fileName)}";
                    image.SaveAs(Path.Combine(Server.MapPath("~/Uploads/"), fileName));
                    blogPost.MediaURL = "/Uploads/" + fileName;
                }

                blogPost.Created = DateTime.Now;
                //Eventually calculate Slug from Title
                db.BlogPosts.Add(blogPost);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(blogPost);
        }

        // GET: BlogPosts/Edit/5
        [Authorize(Roles = "Admin, Moderator")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // POST: BlogPosts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Slug,Body,Abstract,Created,Published,Category,MediaURL")] BlogPost blogPost, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                var slug = StringUtilities.URLFriendly(blogPost.Title);

                if (slug != blogPost.Slug)
                {
                    if (String.IsNullOrWhiteSpace(slug))
                    {
                        ModelState.AddModelError("Title", "Invalid Title");
                        return View(blogPost);
                    }
                    if (db.BlogPosts.Any(p => p.Slug == slug))
                    {
                        ModelState.AddModelError("Title", "The title must be unique");
                        return View(blogPost);
                    }
                    blogPost.Slug = slug;
                }

                if (ImageUploadValidator.IsWebFriendlyImage(image))
                {
                    var fileName = Path.GetFileName(image.FileName);
                    image.SaveAs(Path.Combine(Server.MapPath("~/Upload/"), fileName));
                    blogPost.MediaURL = "~/Uploads/" + fileName;
                }

                blogPost.Updated = DateTime.Now;
                db.Entry(blogPost).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(blogPost);
        }

        // GET: BlogBlogPosts/Delete/5
        [Authorize(Roles = "Admin, Moderator")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // POST: BlogPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BlogPost blogPost = db.BlogPosts.Find(id);
            db.BlogPosts.Remove(blogPost);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult _BtnBlogNav()
        {
            return PartialView(db.BlogPosts.Where(b => b.Published).OrderByDescending(b => b.Created).Skip(6).Take(6).ToList());
        }
        public ActionResult Archive(int? page, string searchStr)
        {
            ViewBag.Search = searchStr;
            var blogList = IndexSearch(searchStr);

            int pageSize = 8;
            int pageNumber = (page ?? 1); //?? null coalescing operator

            return View(blogList.Where(b => b.Published).OrderBy(b => b.Created).ToPagedList(pageNumber, pageSize));
        }

        public ActionResult _RecentPostsFooter()
        {
            return PartialView(db.BlogPosts.Where(b => b.Published).OrderByDescending(b => b.Created).Take(3).ToList());
        }

      
    }
}

Views/Shared/_BtnBlogNav.cshtml
@*@using PagedList;
@using PagedList.Mvc;*@
@using wc_Blog.Models
@model ICollection<BlogPost>


	<div class="row">
		@foreach (var post in Model)
		{
			<div class="col-md-6">
				<a href=@Url.Action("Details", "BlogPosts", new { slug = post.Slug }) class="blog-entry element-animate" data-animate-effect="fadeIn">
					@if (post.MediaURL != null)
					{
						<img class="img-responsive" src="@post.MediaURL" alt="" />
					}
					else
					{
						<img src="/images/img_5.jpg" alt="Image placeholder">
					}
					<div class="blog-content-body">
						<div class="post-meta">
							<span class="category">@post.Category</span>
							<span class="mr-2">@post.Created.ToString("MMM dd yyyy") </span> &bullet;
							<span class="ml-2"><span class="fa fa-comments"></span> @post.Comments.Count</span>
						</div>
						<h2>@post.Title</h2>
					</div>
				</a>
			</div>
		}
	</div>



	@*<div class="row">
			<div class="col-md-12 text-center">
				<nav aria-label="Page navigation" class="text-center">
					<ul class="pagination">
						<li class="page-item"><button class="page-link" type="submit" name="displayNumber" value="2">Prev</button></li>
						<li class="page-item"><button class="page-link" type="submit" name="displayNumber" value="1">1</button></li>
						<li class="page-item"><button class="page-link" type="submit" name="displayNumber" value="2">2</button></li>
						<li class="page-item"><button class="page-link" type="submit" name="displayNumber" value="3">3</button></li>
						<li class="page-item"><button class="page-link" type="submit" name="displayNumber" value="2">Next</button></li>
					</ul>
				</nav>
			</div>
		</div>*@
@*@Html.PagedListPager(Model, page => Url.Action("_BtnBlogNav", new { page }))*@

Views/Shared/_Layout.cshtml
@using wc_Blog.Utilities
<!doctype html>
<html lang="en">
<head>

	<link rel="icon"
		  type="image/png"
		  href="~/images/favicon.ico">
	<title>Wadin' Through It</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="~/Content/PagedList.css" rel="stylesheet" />

	<link href="//fonts.googleapis.com/css?family=Josefin+Sans:500, 400,700" rel="stylesheet">

	<link rel="stylesheet" href="/Content/bootstrap.css">
	<link rel="stylesheet" href="/Content/animate.css">
	<link rel="stylesheet" href="/Content/owl.carousel.min.css">

	<link rel="stylesheet" href="/Content/ionicons.min.css">
	<link rel="stylesheet" href="/Content/font-awesome.min.css">
	<link rel="stylesheet" href="/Content/flaticon.css">

	<!-- Theme Style -->
	<link rel="stylesheet" href="/Content/style.css">
</head>
<body>



	<header role="banner">
		<div class="top-bar">
			<div class="container">
				<div class="row">
					<div class="col-9 social">
						<a href="https://www.linkedin.com/in/wade-cranford-3056b31b2/" target="_blank"><span class="fa fa-linkedin"></span></a>
						<a href="https://github.com/wadecran" target="_blank"><span class="fa fa-github"></span></a>
						<a href="https://wc-portfolio.netlify.app/" target="_blank"><img class="personal-icon" src="~/images/favicon-16x16.png" /></a>
					</div>
					<div class="col-3 search-top">
						<!-- <a href="#"><span class="fa fa-search"></span></a> -->
						@using (Html.BeginForm("Archive", "BlogPosts", FormMethod.Get, new { @class = "search-top-form" }))
						{
							<i class="icon fa fa-search"></i>
							<input id="s" name="searchStr" class="input-block-level form-control" type="text" placeholder="Type a keyword and hit enter" />

						}

					</div>

				</div>
			</div>
		</div>

		<a href=@Url.Action("Index", "Home")><img id="banner" src="~/images/wade-banner.jpg" /></a>
		<nav class="navbar navbar-expand-md  navbar-light bg-light">
			<div class="container">


				<div class="collapse navbar-collapse" id="navbarMenu">
					<ul class="navbar-nav mx-auto">
						<li class="nav-item">
							<a class="nav-link @Html.IsActive("Home", "Index")" href=@Url.Action("Index","Home")>Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link @Html.IsActive("Home", "About")" href=@Url.Action("About","Home")>About</a>
						</li>
						<li class="nav-item">
							<a class="nav-link @Html.IsActive("Home", "Contact")" href=@Url.Action("Contact","Home")>Contact</a>
						</li>
						<li class="nav-item">
							<a class="nav-link @Html.IsActive("BlogPosts", "Archive")" href="@Url.Action("Archive", "Blogposts")">Archive</a>
						</li>
						@if (User.IsInRole("Admin") || User.IsInRole("Moderator"))
						{
							<li class="nav-item">
								<a class="nav-link @Html.IsActive("BlogPosts", "Index")" href="@Url.Action("Index", "Blogposts")">Index</a>
							</li>
							if (User.IsInRole("Admin"))
							{
								<li class="nav-item">
									<a class="nav-link @Html.IsActive("BlogPosts", "Create")" href=" @Url.Action("Create", "Blogposts")">Write</a>
								</li>
							}
						}


						@Html.Partial("_LoginPartial")
					</ul>

				</div>
			</div>
		</nav>
	</header>
	<!-- END header -->

	@RenderBody()


	<footer class="site-footer">
		<div class="container">
			<div class="row mb-5">
				<div class="col-md-4">
					<h3>Thanks for stopping by!</h3>
					<p>
						<img src="~/images/wade-pool-c.jpg" alt="Image placeholder" class="img-fluid" />
					</p>

					<p>
						I appreciate you taking the time to visit my blog, and maybe even read what I have to say. This page started as a way to practice the basics of ASP.NET, but will continue to serve as a journal
						of all of my coding adventures and possibly some of my other interests. So come back soon, and see if there's anything that peeks your own interests.
					</p>
				</div>
				<div class="col-md-6 ml-auto">
					<div class="row">
						<div class="col-md-7">
							<h3>Latest Post</h3>
							<div class="post-entry-sidebar">
								<ul>
									@Html.Action("_RecentPostsFooter", "BlogPosts")
								</ul>
							</div>
						</div>
						<div class="col-md-1"></div>

						<div class="col-md-4">

							<div class="mb-5">
								<h3>Quick Links</h3>
								<ul class="list-unstyled">
									<li><a href="/Home/Index" @Html.IsActive("Home", "Index")>Home</a></li>
									<li><a href="/Home/About" @Html.IsActive("About", "Index")>About</a></li>
									<li><a href="/Home/Contact" @Html.IsActive("Contact", "Index")>Contact</a></li>
								</ul>
							</div>

							<div class="mb-5">
								<h3>Social</h3>
								<ul class="list-unstyled footer-social">
									<li><a href="https://www.linkedin.com/in/wade-cranford-3056b31b2/" target="_blank"><span class="fa fa-linkedin"></span></a></li>
									<li><a href="https://github.com/wadecran" target="_blank"><span class="fa fa-github"></span></a></li>
									<li><a href="https://wc-portfolio.netlify.app/" target="_blank"><img src="~/images/favicon-16x16.png" /></a></li>

								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
					Copyright &copy;
					<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
					Modified By Wade Cranford
					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
				</div>
			</div>
		</div>
	</footer>
	<!-- END footer -->
	<!-- loader -->
	<div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214" /></svg></div>


	<script src="~/Scripts/jquery-3.2.1.min.js"></script>
	<script src="~/Scripts/jquery-migrate-3.0.0.js"></script>
	<script src="~/Scripts/popper.min.js"></script>
	<script src="~/Scripts/bootstrap.min.js"></script>
	<script src="~/Scripts/owl.carousel.min.js"></script>
	<script src="~/Scripts/jquery.waypoints.min.js"></script>
	<script src="~/Scripts/jquery.stellar.min.js"></script>
	<script src="~/Scripts/JavaScript.js"></script>

	<script src="~/Scripts/main.js"></script>
	@RenderSection("Scripts", false)
</body>
</html>

Views/Shared/_RecentPostsFooter.cshtml
@using wc_Blog.Models
@model IEnumerable<BlogPost>

@foreach (var post in Model)
{
	if (post.MediaURL != null)
	{
	<li>
		<a href="@Url.Action("Details", "BlogPosts", new { slug = post.Slug })">
			<img src="@post.MediaURL" alt="Image placeholder" class="mr-4">
			<div class="text">
				<h4>@post.Title</h4>
				<div class="post-meta">
					<span class="mr-2">@post.Created.ToString("MMM dd yyyy") </span> &bullet;
					<span class="ml-2"><span class="fa fa-comments"></span> @post.Comments.Count </span>
				</div>
			</div>
		</a>
	</li>
	}
	else
	{
	<li>
		<a href="@Url.Action("Details", "BlogPosts", new { slug = post.Slug })">
			<img src="~/images/img_8.jpg" alt="Image placeholder" class="mr-4">
			<div class="text">
				<h4>@post.Title</h4>
				<div class="post-meta">
					<span class="mr-2">@post.Created.ToString("MMM dd yyyy") </span> &bullet;
					<span class="ml-2"><span class="fa fa-comments"></span> @post.Comments.Count </span>
				</div>
			</div>
		</a>
	</li>
	}
}

Views/Shared/_SideNav.cshtml
@using wc_Blog.Utilities
<div class="col-md-12 col-lg-4 sidebar">
	<div class="sidebar-box search-form-wrap">

		@using (Html.BeginForm("Archive", "BlogPosts", FormMethod.Get, new { @class = "form-group search-form" }))
		{
			<div class="form-group">
				<i class="icon fa fa-search"></i>
				<input id="s" name="searchStr" class="input-block-level form-control" type="text" placeholder="Type a keyword and hit enter" />
			</div>

		}
	</div>
	<!-- END sidebar-box -->
	<div class="sidebar-box">
		<div class="bio text-center">
			<img src="~/images/DefaultAvatar.png" alt="Image Placeholder" class="img-fluid">
			<div class="bio-body">
				<h2>Wade Cranford</h2>
				<p>I'm a Full-Stack .NET Developer and I love to explore new technologies. I've been dedicated to studying code for almost two years, but have been exposed to programming since I was young.</p>
				<p><a href="/Home/About" class="btn btn-primary btn-sm">Read my bio</a></p>
				<p class="social">

					<a href="https://www.linkedin.com/in/wade-cranford-3056b31b2/" target="_blank" class="p-2"><span class="fa fa-linkedin"></span></a>
					<a href="https://github.com/wadecran" target="_blank" class="p-2"><span class="fa fa-github"></span></a>
					<a href="https://wc-portfolio.netlify.app/" target="_blank" class="p-2"><img class="personal-icon" src="~/images/favicon-16x16.png" /></a>
				</p>
			</div>
		</div>
	</div>

	<!-- END sidebar-box -->

</div>
<!-- END sidebar -->